apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- secret.yaml

helmCharts:
- name: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  version: 41.7.1
  releaseName: monitoring-system
  namespace: monitoring-system
  valuesFile: values.yaml
  includeCRDs: true

patchesJson6902:
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: prometheuses.monitoring.coreos.com
    patch: |-
      - op: add
        path: "/metadata/annotations/argocd.argoproj.io~1sync-options"
        value: "Replace=true"