apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-system-matrix-alertmanager
  labels:
    app: matrix-alertmanager
    app.kubernetes.io/instance: monitoring-system
    app.kubernetes.io/name: matrix-alertmanager
    argocd.argoproj.io/instance: monitoring-system
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: monitoring-system
      app.kubernetes.io/name: matrix-alertmanager
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: monitoring-system
        app.kubernetes.io/name: matrix-alertmanager
    spec:
      containers:
      - name: matrix-alertmanager
        image: jaywink/matrix-alertmanager:latest
        ports:
        - containerPort: 3000
        env:
          - name: APP_PORT
            value: "3000"
          - name: APP_ALERTMANAGER_SECRET
            value: veryverysecretkeyhere
          - name: MATRIX_HOMESERVER_URL
            value: https://matrix.tribz.cloud
          - name: MATRIX_ROOMS
            value: 'matrix/!Q7iSV7EXDYsgrSsn:matrix.tribz.cloud'
          - name: MATRIX_TOKEN
            value: 0j9-eRla4cHCwLULwcrf_heM8gynEx8tykSc33QgkVE
          - name: MATRIX_USER
            value: botalertmanager
          - name: MENTION_ROOM
            value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-system-matrix-alertmanager
  labels:
    app.kubernetes.io/instance: monitoring-system
    app.kubernetes.io/name: matrix-alertmanager
    argocd.argoproj.io/instance: monitoring-system
spec:
  selector:
    app.kubernetes.io/instance: monitoring-system
    app.kubernetes.io/name: matrix-alertmanager
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 3000