# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Khue's Homelab
copyright: Copyright &copy; 2020 - 2024 Khue Doan

repo_url: https://github.com/khuedoan/homelab

theme:
  favicon: https://github.com/khuedoan/homelab/assets/27996771/d33be1af-3687-4712-a671-4370da13cc92
  name: material
  palette:
    primary: black
  features:
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - search.highlight
    - search.share

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
  - def_list
  - pymdownx.tasklist:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Installation:
    - installation/sandbox.md
    - Production:
      - installation/production/prerequisites.md
      - installation/production/external-resources.md
      - installation/production/configuration.md
      - installation/production/deployment.md
    - installation/post-installation.md
  - Getting started:
    - getting-started/vpn-setup.md
    - getting-started/user-onboarding.md
    - getting-started/install-pre-commit-hooks.md
  - Concepts:
    - concepts/pxe-boot.md
    - concepts/secrets-management.md
    - concepts/certificate-management.md
    - concepts/development-shell.md
    - concepts/testing.md
  - How-to guides:
    - how-to-guides/alternate-dns-setup.md
    - how-to-guides/expose-services-to-the-internet.md
    - how-to-guides/backup-and-restore.md
    - how-to-guides/use-both-github-and-gitea.md
    - how-to-guides/add-or-remove-nodes.md
    - how-to-guides/run-commands-on-multiple-nodes.md
    - how-to-guides/single-node-cluster-adjustments.md
    - how-to-guides/disable-dhcp-proxy-in-dnsmasq.md
    - how-to-guides/media-management.md
    - how-to-guides/updating-documentation.md
    - Troubleshooting:
      - how-to-guides/troubleshooting/pxe-boot.md
  - Reference:
    - Architecture:
      - reference/architecture/overview.md
      - reference/architecture/networking.md
      - reference/architecture/decision-records.md
    - reference/license.md
    - reference/changelog.md
    - reference/roadmap.md
    - reference/contributing.md
    - reference/faq.md
