apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-secrets
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: grafana-secrets
  data:
    - secretKey: GRAFANA_SSO_CLIENT_SECRET
      remoteRef:
        key: dex.grafana
        property: client_secret
