k3s_kubelet_extra_args:
  - kube-reserved=cpu=300m,memory=300Mi,ephemeral-storage=1Gi
  - system-reserved=cpu=100m,memory=50Mi,ephemeral-storage=1Gi
  - eviction-hard=memory.available<300Mi,nodefs.available<10%
