# TODO create user and access token
# users:
#   - name: renovate
#     fullName: Renovate
#     email: bot@renovateapp.com
#     tokenSecretRef: renovate-secret # ???
organizations:
  - name: ops
    description: Operations
    teams:
      - name: Owners
        members:
          - renovate
repositories:
  - name: homelab
    owner: ops
    private: false
    migrate:
      source: https://github.com/khuedoan/homelab
      mirror: false
    hook: true
  - name: blog
    owner: khuedoan
    migrate:
      source: https://github.com/khuedoan/blog
      mirror: true
    hook: true
  - name: backstage
    owner: khuedoan
    migrate:
      source: https://github.com/khuedoan/backstage
      mirror: true
