#https://github.com/democratic-csi/democratic-csi/pkgs/container/democratic-csi#multiple-deployments
democratic-csi:
  driver:
    config:
      driver: zfs-local-dataset

      zfs:
        # total volume name (zvol/<datasetParentName>/<pvc name>) length cannot exceed 63 chars
        # https://www.ixsystems.com/documentation/freenas/11.2-U5/storage.html#zfs-zvol-config-opts-tab
        # standard volume naming overhead is 46 chars
        # datasetParentName should therefore be 17 chars or less when using TrueNAS 12 or below
        datasetParentName: datasets/k8s/l/v
        detachedSnapshotsDatasetParentName: datasets/k8s/l/s

        datasetProperties:
          compression: lz4
          "grigri:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
        datasetEnableQuotas: true
        datasetEnableReservation: false

  csiDriver:
    name: "org.democratic-csi.zfs-local-dataset"
    storageCapacity: true
    fsGroupPolicy: File

  controller:
    enabled: true
    strategy: node
    externalProvisioner:
      image: registry.k8s.io/sig-storage/csi-provisioner:v3.4.0
      extraArgs:
        - --leader-election=false
        - --node-deployment=true
        - --node-deployment-immediate-binding=true
        - --feature-gates=Topology=true
        - --strict-topology=true
        - --enable-capacity=true
        - --capacity-ownerref-level=1

    externalResizer:
      enabled: false

    externalSnapshotter:
      enabled: true
      image: registry.k8s.io/sig-storage/csi-snapshotter:v6.2.1
      extraArgs:
        - --leader-election=false
        - --node-deployment=true

  node:
    driver:
      enabled: true
      image: ghcr.io/democratic-csi/democratic-csi:v1.8.3
      logLevel: info
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
    nodeSelector:
      name: grigri

  storageClasses:
    - name: zfs-local-dataset
      defaultClass: true
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: false
      parameters:
        fsType: zfs

  volumeSnapshotClasses:
    - name: zfs-local-dataset
      parameters:
        detachedSnapshots: "false"
