hajimari:
  image:  # TODO remove this https://github.com/toboshii/hajimari/blob/main/charts/hajimari/values.yaml
    tag: v0.2.0
  env:
    TZ: Asia/Ho_Chi_Minh
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: 'false'
      hosts:
        - host: &host home.khuedoan.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: hajimari-tls-certificate
          hosts:
            - *host
  hajimari:
    defaultEnable: true
    namespaceSelector:
      any: true
    groups:
      - name: Homelab
        links:
          - name: Documentation
            url: https://homelab.khuedoan.com
          - name: Public GitHub repository
            url: https://github.com/khuedoan/homelab
      - name: Managed services
        links:
          - name: Terraform Cloud
            url: https://app.terraform.io
          - name: Cloudflare
            url: https://dash.cloudflare.com
