hajimari:
  env:
    TZ: Asia/Ho_Chi_Minh
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: 'false'
      hosts:
        - host: &host home.127-0-0-1.nip.io
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: hajimari-tls-certificate
          hosts:
            - *host
  hajimari:
    defaultEnable: true
    namespaceSelector:
      any: true
    globalBookmarks:
      - group: Homelab
        bookmarks:
          - name: Documentation
            url: https://homelab.127-0-0-1.nip.io
          - name: Public GitHub repository
            url: https://github.com/khuedoan/homelab
      - group: Managed services
        bookmarks:
          - name: Terraform Cloud
            url: https://app.terraform.io
          - name: Cloudflare
            url: https://dash.cloudflare.com
  persistence:
    data:
      enabled: false
