apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tekton-triggers

resources:
  - namespace.yaml
  # Triggers
  - https://storage.googleapis.com/tekton-releases/triggers/latest/release.yaml
  - https://storage.googleapis.com/tekton-releases/triggers/latest/interceptors.yaml
  