seafile:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Seafile
        hajimari.io/icon: google-drive
      hosts:
        - host: &host seafile.127-0-0-1.nip.io
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: seafile-tls-certificate
          hosts:
            - *host
  mariadb:
    enabled: true
