seafile:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host seafile.khuedoan.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: seafile-tls-certificate
          hosts:
            - *host
  mariadb:
    enabled: true
