openspeedtest:
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 50m
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: Speedtest
      hajimari.io/icon: speedometer
    hosts:
      - host: &host speedtest.khuedoan.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: speedtest-tls-certificate
        hosts:
          - *host
