trow:
  trow:
    domain: registry.k8s.grigri
    # user: user
    # password: password
    validation:
      enabled: false
      allowDocker: false
      allowKubernetes: true
      allowPrefixes: []
      allowImages: []
      disallowLocalPrefixes: []
      disallowLocalImages: []
      proxyDockerHub: false

  ingress:
    enabled: false  # TODO https://github.com/ContainerSolutions/trow/issues/282
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/proxy-body-size: '0'
      hajimari.io/enable: 'false'
    hosts:
      - host: &host registry.k8s.grigri
        paths:
          - /
    tls:
      - secretName: trow-tls-certificate
        hosts:
          - *host
  volumeClaim:
    storageClassName: longhorn
