---
apiVersion: v1
data:
  message.j2: |
    {%- set
      emojis = {
        'resolved' : 'âœ…',
        'critical' : 'ğŸ”´',
        'severe' : 'ğŸ”´',
        'warning' : 'âš ï¸',
        'unknown' : 'âšªï¸'
      }
    -%}
    {%- if alert.status == 'resolved' -%}
    {{ emojis[alert.status] }}
    {%- else -%}
    {{ emojis[alert.labels.severity] }}
    {%- endif -%}
     *{{ alert.labels.alertname }}*
    {% if alert.annotations.message -%}
    _{{ alert.annotations.message }}_
    {% else -%}
    _{{ alert.annotations.description }}_
    {% endif -%}
    [Prometheus]({{ alert.generatorURL }})
    {% if 'runbook_url' in alert.annotations -%}
    [Runbook URL]({{ alert.annotations.runbook_url }})
    {%- endif -%}
kind: ConfigMap
metadata:
  name: alertmanager-forwarder-template
  namespace: monitoring
