renovate:
  cronjob:
    schedule: '0 9 1 * *'  # At 09:00 every month
  renovate:
    # TODO generate token automatically, this is just for testing
    config: |
      {
        "platform": "gitea",
        "endpoint": "https://git.khuedoan.com/api/v1",
        "gitAuthor": "Renovate Bot <bot@renovateapp.com>",
        "autodiscover": true
      }
  existingSecret: renovate-secret
