[package]
name = "index"
version = "0.1.0"
authors = ["Khue Doan <khuedoan98@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
