apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Pipeline
- https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
# Triggers
- https://storage.googleapis.com/tekton-releases/triggers/latest/release.yaml
- https://storage.googleapis.com/tekton-releases/triggers/latest/interceptors.yaml
# Dashboard
- https://storage.googleapis.com/tekton-releases/dashboard/latest/tekton-dashboard-release.yaml
# Additional
- ingress.yaml
- cluster-role-binding.yaml
- service-account.yaml
# Tasks
- https://raw.githubusercontent.com/tektoncd/catalog/main/task/git-clone/0.5/git-clone.yaml
- https://raw.githubusercontent.com/tektoncd/catalog/main/task/kaniko/0.5/kaniko.yaml
- https://raw.githubusercontent.com/tektoncd/catalog/main/task/pull-request/0.1/pull-request.yaml
