---
prepare_username: agil
prepare_domain: grigri

prepare_password: "{{ lookup('passwordstore', 'kubernetes.grigri/prepare_password')}}"
prepare_public_keys:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCt9TPDP21ho3kQ9q2or9zyqvbsZn4oa0FAUy4t6AmE+Iedx8EIlJDDtlXXKnNGZADcoIrGqCmCjMH4tOcR41Wmv5Jk+A2r2+jX0St7z+QGxWrAZZueK6XMojVWz0Xi0KDdDITMtpafvz1Lg0xDkdfGQZilxbo9qSdQZ0i3nHJzeMrUcZJ1YrJMgeAObgeY3wMAwvcg9YmjHomhbEt59Lp9nq+spqvEipefKJNf79uo9ndAq1b5cxx4QM3qcdmWTn4ZaapiouhFQr4TurslszIJJuazWXYwY8AaMw/jzCj5IEU5dqGB7FVBIR9tGdZFFUq88Ecw6nN/tO2gJ6AWigiP agil@z800"
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0wMbrQuyoHmB0iwfKH5KmlOZcf15Iov4mVVaj23IK7TXFaXLyv2eq6gtxnp6U2kHR062aZH3ueCww+4cb+INpByxf1grsZcfnNL7ePlaGw0xB3GiK3DILH5queAJZD/RUgyVksd7y/he+GdTJMBJN96r/LpZDtUyggOfrhJXYWXQ0NV/IyToZW15Z0dS17CxXhwS3iByLcazWj2zAnxICIS5JJfSBIC+3PrLQnZ38A3y3u4/Sfv+zRK37s9Thh6RyF6OUcWNejgGda8eXRzf6d1jz06TQXDVxWoE3MNganx546xNRqiHq103pJwpdqBBF8hmhcP+caw/2k2GCT4X/ agil@x240"

prepare_custom_cas:
  - name: grigri
    cert: |
      -----BEGIN CERTIFICATE-----
      MIIEOTCCAyGgAwIBAgIBADANBgkqhkiG9w0BAQsFADBxMQswCQYDVQQGEwJFUzEP
      MA0GA1UECBMGTWFkcmlkMQ8wDQYDVQQHEwZNYWRyaWQxDzANBgNVBAoTBmdyaWdy
      aTEhMB8GCSqGSIb3DQEJARYScGFuZG84NTVAZ21haWwuY29tMQwwCgYDVQQDEwNW
      UE4wHhcNMTcwNDIzMDgwNjI1WhcNMjcwNDIxMDgwNjI1WjBxMQswCQYDVQQGEwJF
      UzEPMA0GA1UECBMGTWFkcmlkMQ8wDQYDVQQHEwZNYWRyaWQxDzANBgNVBAoTBmdy
      aWdyaTEhMB8GCSqGSIb3DQEJARYScGFuZG84NTVAZ21haWwuY29tMQwwCgYDVQQD
      EwNWUE4wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC1WrvmJamQlK9G
      dcRrBgkBuSwvCPz1ezbOcjd39Hf0GRfeZqLhD3fs1Mv+RNriBDMuG4enh+CV1QAo
      44nxsawHDbHRuePXcmoh1bjT59AVmL5AlnuFfi2X/69YpDSVSl0P0RSFxysSTzZz
      67Ex/NIt8I5eBTG/ed3yGMXOztGNn0XSMZ1VRs1dS9YB5uMOUmAbJgBWmbb9alQB
      ljs5beOGezJcJHuKY24MMPyAFUfij1NvPOFOeMbFhxTxceBPA3Mp513xYgl6Eucp
      kLS9oeStYObJiLS4Mx1jZR2LISiU5h4+mG142HXFBRxjhM4wgqM1N+Dqu+pRpsCW
      eEbtzlRNAgMBAAGjgdswgdgwHQYDVR0OBBYEFBmwRtVkPDh1nHndbYYxk/U4u5OO
      MIGbBgNVHSMEgZMwgZCAFBmwRtVkPDh1nHndbYYxk/U4u5OOoXWkczBxMQswCQYD
      VQQGEwJFUzEPMA0GA1UECBMGTWFkcmlkMQ8wDQYDVQQHEwZNYWRyaWQxDzANBgNV
      BAoTBmdyaWdyaTEhMB8GCSqGSIb3DQEJARYScGFuZG84NTVAZ21haWwuY29tMQww
      CgYDVQQDEwNWUE6CAQAwDAYDVR0TBAUwAwEB/zALBgNVHQ8EBAMCAQYwDQYJKoZI
      hvcNAQELBQADggEBAJd02ob4xmgngDS+vLmJsTqb5sXSWsa5TvfIZrdj0b24I21s
      IE5+Ju9TKcUZptPF8wu3gHXesYDGuaTLIBf2dfpx6PNg+cGyFKlowVia+ag6BqxE
      saZpQSC6/w8irc47+ZzEOGqJjUQT1WCXXNXMfSNR3PflrS+PVq11a2mwQRjUyOBt
      1vU/ZwDe2nfohQTkcCHgzk9a+rnjpUh6SW0nn5sd91khOf2dqqwmy8Q8q6dbg75f
      3yldsQKIOTcn9yu0vjE+PgIoXll8nCHoe+4vGXXGaBwLgYzTRP4FPpTt9pB52A4r
      fU4KqEv/GTabVBmyUg0VV9fq0LT+IO+aKFmIIFI=
      -----END CERTIFICATE-----
