iso_url: "https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/34.20210626.3.2/x86_64/fedora-coreos-34.20210626.3.2-live.x86_64.iso"
iso_checksum: "sha256:da01be330488653d319995f2d9a065c9f45443f806b50e4b11fd5622d88c3642"
iso_file_name: "fedora-coreos-34.20210626.3.2-live.x86_64.iso"

os_name: CoreOS
# TODO (optimize) Get timezone automatically from the controller
timezone: Asia/Ho_Chi_Minh
