app-template:
  controller:
    # HA is not supported
    replicas: 1
    type: statefulset

  image:
    repository: pando85/389ds
    tag: 2.2.5
  env:
    DS_ERRORLOG_LEVEL: "266354688"
    DS_SUFFIX_NAME: dc=grigri,dc=cloud
  envFrom:
    - secretRef:
        name: ldap-secret
  service:
    main:
      type: LoadBalancer
      loadBalancerIP: 192.168.193.3
      externalTrafficPolicy: Local
      ports:
        http:
          enabled: false
        ldap:
          primary: true
          port: 389
          protocol: TCP
          targetPort: 3389
        ldaps:
          port: 636
          protocol: TCP
          targetPort: 3636

  initContainers:
    chown:
      image: busybox:1.36.0
      command: ["sh", "-c", "chown -R 389:389 /data"]
      volumeMounts:
        - name: data
          mountPath: /data

  ingress:
    main:
      enabled: false

  podSecurityContext:
    fsGroup: 389

  volumeClaimTemplates:
    - name: data
      mountPath: /data
      accessMode: "ReadWriteOnce"
      size: 1.5Gi
      storageClass: longhorn-ssd
  persistence:
    certs:
      enabled: true
      type: secret
      name: ldap-certs
      mountPath: /data/tls
      readOnly: true
    ca:
      enabled: true
      type: secret
      name: ldap-ca
      mountPath: /data/tls/ca
      readOnly: true
  resources:
    requests:
      cpu: 50m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi
