harbor:
  expose:
    type: ingress
    ingress:
      hosts:
        core: core.harbor.tribz.cloud
        notary: notary.harbor.tribz.cloud
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Harbor
        hajimari.io/icon: git
    tls:
      enabled: true
      certSource: secret
      secret:
        secretName: harbor-tls-certificate
        notarySecretName: harbor-notary-tls-certificate
  externalURL: https://core.harbor.tribz.cloud