# Gitea
- path: gitea/admin
  data:
    - key: password
      length: 32
      special: true

# Dex
- path: dex/grafana
  data:
    - key: client_secret
      length: 32
      special: false

# Trow
- path: trow/admin
  data:
    - key: password
      length: 32
      special: true
