# Gitea
- name: gitea.admin
  data:
    - key: password
      length: 32
      special: true
- name: gitea.renovate
  data:
    - key: token
      length: 32
      special: false

# Dex
- name: dex.grafana
  data:
    - key: client_secret
      length: 32
      special: false
- name: dex.gitea
  data:
    - key: client_secret
      length: 32
      special: false
- name: kanidm.dex
  data:
    - key: client_id
      length: 32
      special: false
    - key: client_secret
      length: 32
      special: false

# Registry
- name: registry.admin
  data:
    - key: password
      length: 32
      special: true

# Woodpecker
- name: woodpecker.agent
  data:
    - key: secret
      length: 32
      special: false
- name: gitea.woodpecker
  data:
    - key: client_id
      length: 32
      special: false
    - key: client_secret
      length: 32
      special: false

# Paperless
- name: paperless.admin
  data:
    - key: PAPERLESS_ADMIN_PASSWORD
      length: 32
      special: true

# Tailscale
- name: external
  data:
    - key: tailscale-auth-key
      length: 32
      special: false
