- hosts: all
  gather_facts: no
  tasks:
    - name: Wait for SSH connection
      wait_for_connection:
        delay: 10

- hosts: all
  become: yes
  roles:
    - name: wireguard
    - name: cloudflared
