authentik:
  authentik:
    secret_key: "dontjudgemethisisjustfortesting" # TODO
    postgresql:
      password: &postgresql_password "IKnowThisIsNotASecurePasswordJust4Testing" # TODO

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
    - host: &host authentik.khuedoan.com
      paths:
      - path: "/"
        pathType: Prefix
    tls:
    - secretName: authentik-tls-certificate
      hosts:
      - *host

  postgresql:
    enabled: true
    postgresqlPassword: *postgresql_password
    persistence:
      enabled: true
      storageClass: longhorn
  redis:
    enabled: true
