woodpecker:
  agent:
    replicaCount: 2
    env:
      WOODPECKER_BACKEND_K8S_STORAGE_RWX: false
      # Agents will spawn pods to run workflow steps using the
      # Kubernetes backend instead of running them directly on
      # the agent pod, so we can run many workflows per agent.
      WOODPECKER_MAX_WORKFLOWS: 10
  server:
    env:
      WOODPECKER_HOST: https://ci.khuedoan.com
      WOODPECKER_WEBHOOK_HOST: http://woodpecker-server.woodpecker
      WOODPECKER_GITEA: true
      WOODPECKER_GITEA_URL: https://git.khuedoan.com
      WOODPECKER_OPEN: true
      WOODPECKER_ADMIN: gitea_admin
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      ingressClassName: nginx
      hosts:
        - host: &host ci.khuedoan.com
          paths:
            - path: /
      tls:
        - secretName: woodpecker-tls-certificate
          hosts:
            - *host
